apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: www-aimhighergg-com
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AbeYuki/aimhighergg-com.git
    targetRevision: HEAD
    path: overlay/prod/
  destination:
    server: https://kubernetes.default.svc
    namespace: www-aimhighergg-com
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-k8s
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AbeYuki/monitoring-k8s.git
    targetRevision: HEAD
    path: overlay/prod/
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redmine-k8s
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AbeYuki/redmine-k8s.git
    targetRevision: HEAD
    path: overlay/prod/
  destination:
    server: https://kubernetes.default.svc
    namespace: prod-redmine
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-aggregator-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AbeYuki/ingress-aggregator.git
    targetRevision: HEAD
    path: overlay/argocd/
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-aggregator-argocd-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AbeYuki/ingress-aggregator.git
    targetRevision: HEAD
    path: overlay/argocd-api/
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-aggregator-dashboard
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AbeYuki/ingress-aggregator.git
    targetRevision: HEAD
    path: overlay/dashboard/
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-aggregator-grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AbeYuki/ingress-aggregator.git
    targetRevision: HEAD
    path: overlay/grafana/
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-aggregator-jupyterlab
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AbeYuki/ingress-aggregator.git
    targetRevision: HEAD
    path: overlay/jupyterlab/
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-aggregator-longhorn
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AbeYuki/ingress-aggregator.git
    targetRevision: HEAD
    path: overlay/longhorn/
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-aggregator-prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AbeYuki/ingress-aggregator.git
    targetRevision: HEAD
    path: overlay/prometheus/
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-aggregator-alertmanager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AbeYuki/ingress-aggregator.git
    targetRevision: HEAD
    path: overlay/alertmanager/
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-aggregator-loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AbeYuki/ingress-aggregator.git
    targetRevision: HEAD
    path: overlay/loki/
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-aggregator-redmine
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AbeYuki/ingress-aggregator.git
    targetRevision: HEAD
    path: overlay/redmine/
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.1.4
    helm:
      releaseName: v4-1-4
      valueFiles:
         - https://raw.githubusercontent.com/AbeYuki/helm/main/ingress-nginx/values_main_on_premises.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ingress-nginx
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: default
  source:
    chart: metallb
    repoURL: https://metallb.github.io/metallb
    targetRevision: 0.12.1
    helm:
      releaseName: v0-12-1
      valueFiles:
         - https://raw.githubusercontent.com/AbeYuki/helm/main/metallb/values_main_on_premises.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: metallb
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: 1.4.0
    helm:
      releaseName: v1-4-0
      valueFiles:
         - https://raw.githubusercontent.com/AbeYuki/helm/main/longhorn/values_main_on_premises.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: longhorn-system
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: 1.11.0
    helm:
      releaseName: v1-11-0
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager