name: '[Production]Terraform Apply on Merge'

on:
  pull_request:
    branches:
      - main
    paths:
      - 'modules/**'
      - 'production/**'
    types:
      - closed

jobs:
  terraform-apply-production:
    runs-on: [self-hosted, kubernetes, arm64]
    if: github.event.pull_request.merged == true && github.actor != 'github-actions[bot]'
    container:
      image: hashicorp/terraform:latest
    steps:
      - name: Install git
        run: |
          apk add --no-cache git
          mkdir -p ~/.kube/
          printf "%s" "${{ secrets.KUBE_CONFIG_PRODUCTION }}" > ~/.kube/config_k3s_node2

      - name: Checkout repository
        run: git clone https://github.com/${{ github.repository }} ${{ github.repository }}

      - name: Initialize Terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform init
        working-directory: ${{ github.repository }}/production

      - name: Terraform Apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform apply -auto-approve
        working-directory: ${{ github.repository }}/production
