name: '[staging]Terraform Plan to Apply'

on:
  push:
    branches:
      - staging

jobs:
  terraform-plan:
    runs-on: [self-hosted, kubernetes]
    container:
      image: hashicorp/terraform:latest
    steps:
      - name: Install git and setup kube config
        run: |
          apk add --no-cache git
          mkdir -p ~/.kube/
          echo -n ${{ secrets.KUBE_CONFIG_STAGING }} > ~/.kube/config_rke_oci

      - name: Checkout repository
        run: git clone https://github.com/${{ github.repository }} ${{ github.repository }}

      - name: Initialize Terraform
        run: terraform init
        working-directory: ${{ github.repository }}/staging

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ${{ github.repository }}/staging

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ${{ github.repository }}/staging
