name: '[staging]Terraform Plan to Apply'

on:
  push:
    branches:
      - staging

jobs:
  terraform-plan-apply-staging:
    runs-on: [self-hosted, kubernetes, arm64]
    container:
      image: hashicorp/terraform:latest
    steps:
      - name: Install git and setup kube config
        run: |
          apk add --no-cache git
          mkdir -p ~/.kube/
          printf "%s" "${{ secrets.KUBE_CONFIG_STAGING }}" > ~/.kube/config_rke_oci

      - name: Checkout repository
        run: git clone -b staging https://github.com/${{ github.repository }} ${{ github.repository }}

      - name: Initialize Terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform init
        working-directory: ${{ github.repository }}/staging

      - name: Terraform Plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform plan -out=tfplan
        working-directory: ${{ github.repository }}/staging

      - name: Terraform Apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform apply -auto-approve
        working-directory: ${{ github.repository }}/staging
