name: Sync staging with main

on:
  workflow_run:
    workflows: 
      - '[Production]Terraform Apply on Merge'
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync-staging-bot:
    runs-on: [self-hosted, kubernetes, arm64]
    if: github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success'
    container:
      image: hashicorp/terraform:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync origin/main to origin/staging
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch origin
          git push origin origin/main:staging --force
