name: Sync staging with main

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync-staging-bot:
    runs-on: [self-hosted, kubernetes, arm64]
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    container:
      image: hashicorp/terraform:latest
    steps:
      - name: Checkout repository
        run: git clone https://github.com/${{ github.repository }} ${{ github.repository }}

      - name: Merge main into staging
        working-directory: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git fetch origin
          git checkout staging 2>/dev/null || git checkout -b staging origin/staging
          git merge --no-ff origin/main -m "github-actions[bot]Merge main into staging"
          git push origin staging
