name: Sync staging with main

on:
  workflow_run:
    workflows: 
      - '[Production]Terraform Apply on Merge'
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync-staging-bot:
    runs-on: [self-hosted, kubernetes, arm64]
    if: github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success'
    container:
      image: hashicorp/terraform:latest
    steps:
      - name: Checkout repository
        run: git clone https://github.com/${{ github.repository }} ${{ github.repository }}

      - name: Sync origin/main to origin/staging
        working-directory: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git fetch origin
          git push origin origin/main:staging --force
