name: Terraform Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: "ap-northeast-1"
  TF_VERSION: "1.5.0"

jobs:
  terraform:
    runs-on: [self-hosted, kubernetes]
    container:
      image: hashicorp/terraform:latest
    steps:
      - name: Install git
        run: apk add --no-cache git

      - name: Clone repository
        run: |
          git clone https://github.com/${{ github.repository }} repo
          ls -la repo

      - name: Set working directory and detect modified directory
        working-directory: repo
        run: |
          if git diff --name-only HEAD^ | grep -q '^production/'; then echo "TF_WORKDIR=production" >> $GITHUB_ENV; fi
          if git diff --name-only HEAD^ | grep -q '^staging/'; then echo "TF_WORKDIR=staging" >> $GITHUB_ENV; fi
          if git diff --name-only HEAD^ | grep -q '^testing/'; then echo "TF_WORKDIR=testing" >> $GITHUB_ENV; fi

      - name: Check Terraform format
        run: terraform fmt -check -recursive
        working-directory: ${{ env.TF_WORKDIR }}
      
      - name: Initialize Terraform
        run: terraform init
        working-directory: ${{ env.TF_WORKDIR }}

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ${{ env.TF_WORKDIR }}
      
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ${{ env.TF_WORKDIR }}
